name: Sonarcloud Scan
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
        #   #Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          # projectBaseDir: TestActions
          args: >
            -Dsonar.organization=cashewhands
            -Dsonar.projectKey=cashewhands_TestActions
            -Dsonar.sources=path
            -Dsonar.exclusions=path/migrations/**
            -Dsonar.tests=tests
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.python.version=3.8
            -Dsonar.dynamicAnalysis=reuseReports
            -Dsonar.python.coverage.reportPaths=cover_xml/*coverage*xml
            -Dsonar.python.xunit.reportPath=test-reports/*cover_report*xml   
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}